#!/bin/bash

# 25.07.2025 - running dorado trim on long-read single cell data 

module load Miniconda2
source activate nanopore
basecalledDir=/lustre/projects/Research_Project-MRC190311/longReadSeq/ONTRNA/Gina/analysis/EX167_scHypothalamus/1_basecalled

dorado-1.0.2-linux-x64/bin/dorado --version
[2025-07-25 11:07:44.277] [info] Running: "--version"
1.0.2+c758d2f6

#---------------------------------------

# dorado trim with default parameters
cd /lustre/projects/Research_Project-MRC148213/lsl693/software
dorado-1.0.2-linux-x64/bin/dorado trim ${basecalledDir}/ex167_hypothalamus_00_merged.fastq --sequencing-kit SQK_LSK114 --emit-fastq > ${basecalledDir}/ex167_hypothalamus_00_merged_trimmed.fastq 

[2025-07-25 10:58:46.719] [info] Running: "trim" "/lustre/projects/Research_Project-MRC190311/longReadSeq/ONTRNA/Gina/analysis/EX167_scHypothalamus/1_basecalled/ex167_hypothalamus_00_merged.fastq" "--sequencing-kit" "SQK_LSK114" "--emit-fastq"
[2025-07-25 10:58:47.277] [info]  - Note: FASTQ output is not recommended as not all data can be preserved.
[2025-07-25 10:58:47.305] [info] > starting adapter/primer trimming
[2025-07-25 11:01:40.105] [info] > Finished in (ms): 172700
[2025-07-25 11:01:40.105] [info] > Reads written: 4263986
[2025-07-25 11:01:40.105] [info] > finished adapter/primer trimming

# original basecalled sequence 
grep -A 1 3b028661-0add-4dd3-8052-96c5a0c7c43e ${basecalledDir}/ex167_hypothalamus_00_merged.fastq

@3b028661-0add-4dd3-8052-96c5a0c7c43e runid=99ca8f753c10156d481724fc3847a82346604173 ch=1168 start_time=2025-05-12T14:33:39.139170+00:00 flow_cell_id=PBC91553 basecall_gpu=Quadro_GV100 protocol_group_id=PM0002_20250512_SC_HYPOTHALAMUS sample_id=A_EX167 parent_read_id=3b028661-0add-4dd3-8052-96c5a0c7c43e basecall_model_version_id=dna_r10.4.1_e8.2_400bps_hac@v4.3.0
GATGTTTATGTCCTGTACTTCGTTCAGTTACGTATTGCTGTTAAGCAGTGGTATCAACGCAGAGTACATGGAAATAGTTGGGGAGGTAAAGAATGTCTTATAATTGTTGCAGATTGCATAGGTATTTAAAAGCAAAAGAGTGATTAACATTTTAACTTGATATTTTTTGGTGGGGGAGGTACAGTTAAATAAGGGTGGAAAGGTTGGGAAATGTGGAATTTAGGAGTATAATTTTAAAAGCCATTTAGTGCAATTGAATGCTAGCTTTCTAAAAGATTTGTGTCGTTAAAAGGAATTTTTTTCTTCCCTGCTTCAATATGGCGACTTTCCTTGTCCTTTTGTCTTCCAAGCGGCGTTGCAGGTTGTGTCTTGACCCATTTTTTTTCCTGTCCTCCCACCTCAACCCTATTTGTTGAGAGGGGTCCAAGTCCTTCCTCCCTTCCCTCTATAGGGAGGATGGGGGTGGTCGATGGTAGCCGGTTGAACCTCCGTTGCAAATTCAGTTCTTCCCTGCAGAAAATTGTTCTTTTTAATATTTTAATTGCTTTAATTTTCACTACGCTCTTACTGATCAAAATAGGTCAAAGATTATTCACGATGGGGAACTGGTTTTTGATTTTTTTTTTTTTTTTTTACTAAAGGCAAATGACTCAAGGTGTAACAGAAAACAAGAAAATCCAATATCAGGATAATCAGACCACCACAGGTTTACAGTTTATAGAAACTAGAGCAGTTCTCACGTTGAGGTCTGTGGAAGAGATGTCCATTGGAGAAATGGCTGGTAGTTACTCTTTTTTCCCCCACCCCCTTAATCAGACTTTAAAAGTGCTTAACCCCTTAAACTTGTTATTTTTTACTTGAAGCATTTTGGGATGGTCTTAACAGGGAAGAGAGAGGGTGGGGGAGAAAATGTTTTTTTCTAAGATTTTCCACAGATGCTATAGTACTATTGACAAACTGGGTTAGAGAAGGAGTGTACCGCTGTGCTGTTGGCACGAACACCTTCAGGGACTGGAGCTGCTTTTATCCTTGGAAGAGTATTCCCAGTTGAAGCTGAAAAGTACAGCACAGTGCAGCTTTGGTTCATATTCAGTCATCTCAGGAGAACTTCAGAAGAGCTTGAGTAGGCCAAATGTTGAAGTTAAGTTTTCCAATAATGTGACTTCTTAAAAGTTTTATTAAAGGGGAGGGGCAAATATTGGCAATTAGTTGGCAGTGGCCTGTTACGGTTGGGATTGGTGGGGTGGGTTTAGGTAATTGTTTAGTTTATGATTGCAGATAAACTCATGCCAGAGAACTTAAAGTCTTAGAATGAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAGTTACTAGAGCAGGTGTAAAGGAAGATCGGAAGAGCGTCGTGTAGTTTAGCAATACA

# reads after dorado trim
grep -A 1 3b028661-0add-4dd3-8052-96c5a0c7c43e ${basecalledDir}/ex167_hypothalamus_00_merged_trimmed.fastq 

@3b028661-0add-4dd3-8052-96c5a0c7c43e
GATGTTTATGTCCTGTACTTCGTTCAGTTACGTATTGCTGTTAAGCAGTGGTATCAACGCAGAGTACATGGAAATAGTTGGGGAGGTAAAGAATGTCTTATAATTGTTGCAGATTGCATAGGTATTTAAAAGCAAAAGAGTGATTAACATTTTAACTTGATATTTTTTGGTGGGGGAGGTACAGTTAAATAAGGGTGGAAAGGTTGGGAAATGTGGAATTTAGGAGTATAATTTTAAAAGCCATTTAGTGCAATTGAATGCTAGCTTTCTAAAAGATTTGTGTCGTTAAAAGGAATTTTTTTCTTCCCTGCTTCAATATGGCGACTTTCCTTGTCCTTTTGTCTTCCAAGCGGCGTTGCAGGTTGTGTCTTGACCCATTTTTTTTCCTGTCCTCCCACCTCAACCCTATTTGTTGAGAGGGGTCCAAGTCCTTCCTCCCTTCCCTCTATAGGGAGGATGGGGGTGGTCGATGGTAGCCGGTTGAACCTCCGTTGCAAATTCAGTTCTTCCCTGCAGAAAATTGTTCTTTTTAATATTTTAATTGCTTTAATTTTCACTACGCTCTTACTGATCAAAATAGGTCAAAGATTATTCACGATGGGGAACTGGTTTTTGATTTTTTTTTTTTTTTTTTACTAAAGGCAAATGACTCAAGGTGTAACAGAAAACAAGAAAATCCAATATCAGGATAATCAGACCACCACAGGTTTACAGTTTATAGAAACTAGAGCAGTTCTCACGTTGAGGTCTGTGGAAGAGATGTCCATTGGAGAAATGGCTGGTAGTTACTCTTTTTTCCCCCACCCCCTTAATCAGACTTTAAAAGTGCTTAACCCCTTAAACTTGTTATTTTTTACTTGAAGCATTTTGGGATGGTCTTAACAGGGAAGAGAGAGGGTGGGGGAGAAAATGTTTTTTTCTAAGATTTTCCACAGATGCTATAGTACTATTGACAAACTGGGTTAGAGAAGGAGTGTACCGCTGTGCTGTTGGCACGAACACCTTCAGGGACTGGAGCTGCTTTTATCCTTGGAAGAGTATTCCCAGTTGAAGCTGAAAAGTACAGCACAGTGCAGCTTTGGTTCATATTCAGTCATCTCAGGAGAACTTCAGAAGAGCTTGAGTAGGCCAAATGTTGAAGTTAAGTTTTCCAATAATGTGACTTCTTAAAAGTTTTATTAAAGGGGAGGGGCAAATATTGGCAATTAGTTGGCAGTGGCCTGTTACGGTTGGGATTGGTGGGGTGGGTTTAGGTAATTGTTTAGTTTATGATTGCAGATAAACTCATGCCAGAGAACTTAAAGTCTTAGAATGAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAGTTACTAGAGCAGGTGTAAAGGAAGATCGGAAGAGCGTCGTGTAGTTTAGCAATACA

#---------------------------------------

# dorado trim with custom primer sequences specifying sequencing kit 
dorado-1.0.2-linux-x64/bin/dorado trim ${basecalledDir}/ex167_hypothalamus_00_merged.fastq --sequencing-kit SQK_LSK114 --primer-sequences ${basecalledDir}/single_cell_generic_primer.fasta --emit-fastq > ${basecalledDir}/ex167_hypothalamus_00_merged_trimmed_customseq.fastq 

[2025-07-25 11:04:50.807] [info] Running: "trim" "/lustre/projects/Research_Project-MRC190311/longReadSeq/ONTRNA/Gina/analysis/EX167_scHypothalamus/1_basecalled/ex167_hypothalamus_00_merged.fastq" "--sequencing-kit" "SQK_LSK114" "--primer-sequences" "/lustre/projects/Research_Project-MRC190311/longReadSeq/ONTRNA/Gina/analysis/EX167_scHypothalamus/1_basecalled/single_cell_generic_primer.fasta" "--emit-fastq"
[2025-07-25 11:04:50.808] [info]  - Note: FASTQ output is not recommended as not all data can be preserved.
[2025-07-25 11:04:50.811] [info] > starting adapter/primer trimming
[2025-07-25 11:04:51.077] [error] Could not extract position from record name.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error parsing custom adapter/primer file.
Aborted (core dumped)

# dorado trim with custom primer sequences not specifying sequencing kit 
dorado-1.0.2-linux-x64/bin/dorado trim ${basecalledDir}/ex167_hypothalamus_00_merged.fastq --primer-sequences ${basecalledDir}/single_cell_generic_primer.fasta --emit-fastq > ${basecalledDir}/ex167_hypothalamus_00_merged_trimmed_customseq.fastq 

[2025-07-25 11:05:23.167] [info] Running: "trim" "/lustre/projects/Research_Project-MRC190311/longReadSeq/ONTRNA/Gina/analysis/EX167_scHypothalamus/1_basecalled/ex167_hypothalamus_00_merged.fastq" "--primer-sequences" "/lustre/projects/Research_Project-MRC190311/longReadSeq/ONTRNA/Gina/analysis/EX167_scHypothalamus/1_basecalled/single_cell_generic_primer.fasta" "--emit-fastq"
[2025-07-25 11:05:23.167] [error] The sequencing kit name must be specified with --sequencing-kit.

# input of custom primers
cat $basecalledDir/single_cell_generic_primer.fasta
>TSO type=primer kits=custom_single_cell
AAGCAGTGGTATCAACGCAGAGTACAT
>ligation_adaptor type=primer kits=custom_single_cell
CCTGTACTTCGTTCAGTTACGTATTGCT
>Read1 type=primer kits=custom_single_cell
AGATCGGAAGAGCGTCGTGTAG